config/routes.rb
Rails.application.routes.draw do

  get 'lists/add_recipe'
  get 'lists/add_ingredient'
  get 'lists/clear'
  resources :lists
  resources :recipes
  resources :ingredients
  get 'pages/home'
  root'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :recipe, optional: true
	belongs_to :list, optional: true
end

app/models/list.rb
class List < ApplicationRecord
	has_many :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients
	accepts_nested_attributes_for :ingredients, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    redirect_to :controller => "lists", :action => "add_ingredient", :id => @ingredient.id
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name,:amount)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.last()
    render "show"
  end

  # GET /lists/1
  # GET /lists/1.json
  def show

  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  def clear
    @list = List.last()
    @list.ingredients.clear
    render "show"
  end

  def add_recipe
    @recipe = Recipe.find(params[:recipe])
    @list = List.last()
    @list.ingredients <<  @recipe.ingredients
    render "show"
  end

  def add_ingredient
    @list = List.last()
    @ingredient = Ingredient.find(params[:id])
    @list.ingredients << @ingredient
    render "show"
  end
  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.fetch(:list, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name,:directions,ingredients_attributes:[:id,:_destroy,:name,:amount])
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<div class="container">
  <div class= "container">
<%= simple_form_for @ingredient do |f| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <!-- simple form for ingredients -->
    <%= f.input :name %>
    <%= f.input :amount %>
  </div>

    <div class="d-flex justify-content-center">
       <div class="actions">
       <%= f.button :submit,'Add to list', class: "btn btn-dark" %>
       </div>
    </div>
<% end %>
</div>
</div>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groceries</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4B515D;">

  <div class="collapse navbar-collapse justify content between" id="navbarNav">

    <!--Buttons -->
    <!-- left side -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </li>
      <li class="navbar-nav active" >
        <%= link_to "Create Recipe", new_recipe_path, class:"navbar-brand" %>
      </li>
      <li class="navbar-nav active" >
        <%= link_to "Add item to list", new_ingredient_path, class:"navbar-brand" %>
      </li>
 	 </ul>


    <!-- right side -->
    <ul class="navbar-nav ml-auto">
    	<li class="nav-item active">
    		<%= link_to "View List", lists_path, class:"navbar-brand" %>
    	</li>
    </ul>


  </div>
</nav>




  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h1> LIST </h1>
	
 <% for @ingredient in @list.ingredients %>
 	<div class="row">
 		<div class="col-md-12">
	 		<div class="d-flex justify-content-center">
				<li><%= @ingredient.name %>:   <%=@ingredient.amount %> </li>
			</div>
		</div>
	</div>
<% end %>

<div class="d-flex justify-content-center">
<%= link_to 'clear', lists_clear_path, class: "btn btn-dark"  %> 
</div>

app/views/pages/home.html.erb
<h1> Home page </h1>

<div class="container">
<div class="row">
	<div class="col-md-6 ">
		<div class="d-flex justify-content-center">
		<%= link_to 'recipes', recipes_path,class: "btn btn-dark" %>
		</div>
	</div>
	<div class="col-md-6">

		<div class="d-flex justify-content-center">
			
			<%= link_to 'View list', lists_path, class: "btn btn-dark" %>
		</div>
	</div>
</div>
</div>

app/views/recipes/_form.html.erb
<div class="container">
  <div class= "container">
<%= simple_form_for @recipe do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- simple form for recipe -->

  <div class="form-group">
  <%= f.input :name %>
  <%= f.input :directions %>
</div>


<br>
  <!-- nested fields for ingredients in the recipe -->
  <div class="form-group">
  <%= f.nested_fields_for :ingredients do |ff| %>
   
    <%= ff.remove_nested_fields_link%>
    <%= ff.input :name %>
    <%= ff.input :amount %>
    <br>
  <% end %>
  <%= f.add_nested_fields_link :ingredients, "Add ingredient" %>
</div>

  <div class="d-flex justify-content-center">
  <div class="actions">
    <%= f.button :submit, class: "btn btn-dark" %>
  </div>
</div>
<% end %>
</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<h1>Recipes </h1>
  <div class="row">
  <% @recipes.each do |recipe| %>
  <div class="col-md-4">
     <div class="recipe-box">
        <ul>
          <li><%= recipe.name %></li>
          <li><%= link_to 'Show', recipe, class: "btn btn-dark" %>
          <%= link_to 'Add to list', {:controller => "lists", :action => "add_recipe", :recipe => recipe.id }, class: "btn btn-dark"%> </li>
        </ul>
    </div>  
    <br>
   </div>
  <% end %>
</div> <!--/row-->
<br>

</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class= "containter">
	<p id="notice"><%= notice %></p>

	<div style="padding-left: 6px">
		<%= link_to 'Back', recipes_path, class: "btn btn-outline-dark" %>
		<%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-outline-dark" %> 

	</div>
	<h1>
	  <%= @recipe.name %>
	</h1>
	<br>
	<div class="row">
		<div class="col" style="text-align: center;">

		<p>
		  <h4 style="color:#4B515D;">directions:</h4>
		  <%= @recipe.directions %>
		</p>
		</div>

		<div class="col" >
			<h3>Ingredients</h3>
			<ul>
			<% for @ingredient in @recipe.ingredients %>
			<li><%= @ingredient.name %>:   <%=@ingredient.amount %> </li>
			<% end %>
			</ul>

		</div>


	</div>

</div>